// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0--rc3
// source: minitwitter.proto

package Mini_Twitterek

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tweet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minitwitter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_minitwitter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_minitwitter_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TweetLicz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Liczba int32 `protobuf:"varint,1,opt,name=Liczba,proto3" json:"Liczba,omitempty"` // Dodajemy pole Liczba
}

func (x *TweetLicz) Reset() {
	*x = TweetLicz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minitwitter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetLicz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetLicz) ProtoMessage() {}

func (x *TweetLicz) ProtoReflect() protoreflect.Message {
	mi := &file_minitwitter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetLicz.ProtoReflect.Descriptor instead.
func (*TweetLicz) Descriptor() ([]byte, []int) {
	return file_minitwitter_proto_rawDescGZIP(), []int{1}
}

func (x *TweetLicz) GetLiczba() int32 {
	if x != nil {
		return x.Liczba
	}
	return 0
}

type TweetList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweet []string `protobuf:"bytes,1,rep,name=Tweet,proto3" json:"Tweet,omitempty"`
}

func (x *TweetList) Reset() {
	*x = TweetList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minitwitter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TweetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetList) ProtoMessage() {}

func (x *TweetList) ProtoReflect() protoreflect.Message {
	mi := &file_minitwitter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetList.ProtoReflect.Descriptor instead.
func (*TweetList) Descriptor() ([]byte, []int) {
	return file_minitwitter_proto_rawDescGZIP(), []int{2}
}

func (x *TweetList) GetTweet() []string {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minitwitter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_minitwitter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_minitwitter_proto_rawDescGZIP(), []int{3}
}

var File_minitwitter_proto protoreflect.FileDescriptor

var file_minitwitter_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x22, 0x1b, 0x0a, 0x05, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x23, 0x0a,
	0x09, 0x54, 0x77, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x63, 0x7a, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x69,
	0x63, 0x7a, 0x62, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4c, 0x69, 0x63, 0x7a,
	0x62, 0x61, 0x22, 0x21, 0x0a, 0x09, 0x54, 0x77, 0x65, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x77, 0x65, 0x65, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x78,
	0x0a, 0x07, 0x54, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x09, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x77, 0x69,
	0x74, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x77, 0x65, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x4c, 0x69,
	0x63, 0x7a, 0x1a, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x2e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x34, 0x6e, 0x65, 0x6b, 0x6b, 0x6b, 0x2f, 0x4d,
	0x69, 0x6e, 0x69, 0x2d, 0x54, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x65, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_minitwitter_proto_rawDescOnce sync.Once
	file_minitwitter_proto_rawDescData = file_minitwitter_proto_rawDesc
)

func file_minitwitter_proto_rawDescGZIP() []byte {
	file_minitwitter_proto_rawDescOnce.Do(func() {
		file_minitwitter_proto_rawDescData = protoimpl.X.CompressGZIP(file_minitwitter_proto_rawDescData)
	})
	return file_minitwitter_proto_rawDescData
}

var file_minitwitter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_minitwitter_proto_goTypes = []interface{}{
	(*Tweet)(nil),     // 0: minitwitter.Tweet
	(*TweetLicz)(nil), // 1: minitwitter.TweetLicz
	(*TweetList)(nil), // 2: minitwitter.TweetList
	(*Empty)(nil),     // 3: minitwitter.Empty
}
var file_minitwitter_proto_depIdxs = []int32{
	0, // 0: minitwitter.Twitter.SendTweet:input_type -> minitwitter.Tweet
	1, // 1: minitwitter.Twitter.GetTweet:input_type -> minitwitter.TweetLicz
	3, // 2: minitwitter.Twitter.SendTweet:output_type -> minitwitter.Empty
	0, // 3: minitwitter.Twitter.GetTweet:output_type -> minitwitter.Tweet
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_minitwitter_proto_init() }
func file_minitwitter_proto_init() {
	if File_minitwitter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_minitwitter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tweet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minitwitter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetLicz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minitwitter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TweetList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minitwitter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minitwitter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minitwitter_proto_goTypes,
		DependencyIndexes: file_minitwitter_proto_depIdxs,
		MessageInfos:      file_minitwitter_proto_msgTypes,
	}.Build()
	File_minitwitter_proto = out.File
	file_minitwitter_proto_rawDesc = nil
	file_minitwitter_proto_goTypes = nil
	file_minitwitter_proto_depIdxs = nil
}
